version: '3.8'

services:
  mcc-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__BlogDbConnection: Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres
      ConnectionStrings__HangfireDbConnection: Host=postgres-hangfire;Port=5432;Database=hangfire;Username=postgres;Password=postgres
    depends_on:
      - postgres
      - postgres-hangfire
        
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  postgres-hangfire:
    image: postgres:latest
    container_name: postgres_hangfire_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hangfire
    ports:
      - "5433:5432"
    volumes:
      - postgres_hangfire_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  postgres_hangfire_data:
    driver: local