version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  postgres-hangfire:
    image: postgres:latest
    container_name: postgres_hangfire_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hangfire
    ports:
      - "5433:5432"
    volumes:
      - postgres_hangfire_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
  postgres_hangfire_data:
    driver: local